/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface CourseSummary {
    id: number;
    slug: string;
    title: string;
    description: string;
    totalModules: number;
    color: string;
    icon: string;
}
export interface ModuleSummary {
    id: number;
    title: string;
    description: string;
    order: number;
    phaseId: number;
}
export interface Phase {
    id: number;
    title: string;
    description: string;
    order: number;
    modules: ModuleSummary[];
}
export interface CourseDetail {
    id: number;
    slug: string;
    title: string;
    description: string;
    color: string;
    icon: string;
    phases: Phase[];
}
export type ResourceType = typeof ResourceType[keyof typeof ResourceType];
export declare const ResourceType: {
    readonly book: "book";
    readonly video: "video";
    readonly film: "film";
    readonly podcast: "podcast";
    readonly website: "website";
    readonly essay: "essay";
};
export interface Resource {
    id: number;
    type: ResourceType;
    title: string;
    /** @nullable */
    author?: string | null;
    /** @nullable */
    url?: string | null;
    /** @nullable */
    description?: string | null;
    isFree: boolean;
}
export interface Exercise {
    id: number;
    title: string;
    description: string;
}
export interface ModuleDetail {
    id: number;
    title: string;
    description: string;
    order: number;
    phaseId: number;
    courseId: number;
    courseSlug: string;
    courseTitle: string;
    phaseName: string;
    resources: Resource[];
    exercises: Exercise[];
}
//# sourceMappingURL=api.schemas.d.ts.map