/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all courses
 */
export declare const GetCoursesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    slug: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodString;
    totalModules: zod.ZodNumber;
    color: zod.ZodString;
    icon: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    slug: string;
    title: string;
    description: string;
    totalModules: number;
    color: string;
    icon: string;
}, {
    id: number;
    slug: string;
    title: string;
    description: string;
    totalModules: number;
    color: string;
    icon: string;
}>;
export declare const GetCoursesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    slug: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodString;
    totalModules: zod.ZodNumber;
    color: zod.ZodString;
    icon: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    slug: string;
    title: string;
    description: string;
    totalModules: number;
    color: string;
    icon: string;
}, {
    id: number;
    slug: string;
    title: string;
    description: string;
    totalModules: number;
    color: string;
    icon: string;
}>, "many">;
/**
 * @summary Get a course with all phases and modules
 */
export declare const GetCourseParams: zod.ZodObject<{
    slug: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    slug: string;
}, {
    slug: string;
}>;
export declare const GetCourseResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    slug: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodString;
    color: zod.ZodString;
    icon: zod.ZodString;
    phases: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        title: zod.ZodString;
        description: zod.ZodString;
        order: zod.ZodNumber;
        modules: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodNumber;
            title: zod.ZodString;
            description: zod.ZodString;
            order: zod.ZodNumber;
            phaseId: zod.ZodNumber;
        }, "strip", zod.ZodTypeAny, {
            id: number;
            title: string;
            description: string;
            order: number;
            phaseId: number;
        }, {
            id: number;
            title: string;
            description: string;
            order: number;
            phaseId: number;
        }>, "many">;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        title: string;
        description: string;
        order: number;
        modules: {
            id: number;
            title: string;
            description: string;
            order: number;
            phaseId: number;
        }[];
    }, {
        id: number;
        title: string;
        description: string;
        order: number;
        modules: {
            id: number;
            title: string;
            description: string;
            order: number;
            phaseId: number;
        }[];
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    slug: string;
    title: string;
    description: string;
    color: string;
    icon: string;
    phases: {
        id: number;
        title: string;
        description: string;
        order: number;
        modules: {
            id: number;
            title: string;
            description: string;
            order: number;
            phaseId: number;
        }[];
    }[];
}, {
    id: number;
    slug: string;
    title: string;
    description: string;
    color: string;
    icon: string;
    phases: {
        id: number;
        title: string;
        description: string;
        order: number;
        modules: {
            id: number;
            title: string;
            description: string;
            order: number;
            phaseId: number;
        }[];
    }[];
}>;
/**
 * @summary Get a module with all resources and exercises
 */
export declare const GetModuleParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetModuleResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    order: zod.ZodNumber;
    phaseId: zod.ZodNumber;
    courseId: zod.ZodNumber;
    courseSlug: zod.ZodString;
    courseTitle: zod.ZodString;
    phaseName: zod.ZodString;
    resources: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        type: zod.ZodEnum<["book", "video", "film", "podcast", "website", "essay"]>;
        title: zod.ZodString;
        author: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isFree: zod.ZodBoolean;
    }, "strip", zod.ZodTypeAny, {
        type: "book" | "video" | "film" | "podcast" | "website" | "essay";
        id: number;
        title: string;
        isFree: boolean;
        description?: string | null | undefined;
        author?: string | null | undefined;
        url?: string | null | undefined;
    }, {
        type: "book" | "video" | "film" | "podcast" | "website" | "essay";
        id: number;
        title: string;
        isFree: boolean;
        description?: string | null | undefined;
        author?: string | null | undefined;
        url?: string | null | undefined;
    }>, "many">;
    exercises: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        title: zod.ZodString;
        description: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        title: string;
        description: string;
    }, {
        id: number;
        title: string;
        description: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    description: string;
    order: number;
    phaseId: number;
    courseId: number;
    courseSlug: string;
    courseTitle: string;
    phaseName: string;
    resources: {
        type: "book" | "video" | "film" | "podcast" | "website" | "essay";
        id: number;
        title: string;
        isFree: boolean;
        description?: string | null | undefined;
        author?: string | null | undefined;
        url?: string | null | undefined;
    }[];
    exercises: {
        id: number;
        title: string;
        description: string;
    }[];
}, {
    id: number;
    title: string;
    description: string;
    order: number;
    phaseId: number;
    courseId: number;
    courseSlug: string;
    courseTitle: string;
    phaseName: string;
    resources: {
        type: "book" | "video" | "film" | "podcast" | "website" | "essay";
        id: number;
        title: string;
        isFree: boolean;
        description?: string | null | undefined;
        author?: string | null | undefined;
        url?: string | null | undefined;
    }[];
    exercises: {
        id: number;
        title: string;
        description: string;
    }[];
}>;
//# sourceMappingURL=api.d.ts.map