/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all courses
 */
export const GetCoursesResponseItem = zod.object({
  "id": zod.number(),
  "slug": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "totalModules": zod.number(),
  "color": zod.string(),
  "icon": zod.string()
})
export const GetCoursesResponse = zod.array(GetCoursesResponseItem)


/**
 * @summary Get a course with all phases and modules
 */
export const GetCourseParams = zod.object({
  "slug": zod.coerce.string()
})

export const GetCourseResponse = zod.object({
  "id": zod.number(),
  "slug": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "color": zod.string(),
  "icon": zod.string(),
  "phases": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "order": zod.number(),
  "modules": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "order": zod.number(),
  "phaseId": zod.number()
}))
}))
})


/**
 * @summary Get a module with all resources and exercises
 */
export const GetModuleParams = zod.object({
  "id": zod.coerce.number()
})

export const GetModuleResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "order": zod.number(),
  "phaseId": zod.number(),
  "courseId": zod.number(),
  "courseSlug": zod.string(),
  "courseTitle": zod.string(),
  "phaseName": zod.string(),
  "resources": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.enum(['book', 'video', 'film', 'podcast', 'website', 'essay']),
  "title": zod.string(),
  "author": zod.string().nullish(),
  "url": zod.string().nullish(),
  "description": zod.string().nullish(),
  "isFree": zod.boolean()
})),
  "exercises": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string()
}))
})


