/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
import type { Phase } from './phase';

export interface CourseDetail {
  id: number;
  slug: string;
  title: string;
  description: string;
  color: string;
  icon: string;
  phases: Phase[];
}
