/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
export interface ModuleSummary {
    id: number;
    title: string;
    description: string;
    order: number;
    phaseId: number;
}
//# sourceMappingURL=moduleSummary.d.ts.map