/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
import type { Exercise } from './exercise';
import type { Resource } from './resource';

export interface ModuleDetail {
  id: number;
  title: string;
  description: string;
  order: number;
  phaseId: number;
  courseId: number;
  courseSlug: string;
  courseTitle: string;
  phaseName: string;
  resources: Resource[];
  exercises: Exercise[];
}
