/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
import type { ModuleSummary } from './moduleSummary';
export interface Phase {
    id: number;
    title: string;
    description: string;
    order: number;
    modules: ModuleSummary[];
}
//# sourceMappingURL=phase.d.ts.map