/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
export type ResourceType = typeof ResourceType[keyof typeof ResourceType];
export declare const ResourceType: {
    readonly book: "book";
    readonly video: "video";
    readonly film: "film";
    readonly podcast: "podcast";
    readonly website: "website";
    readonly essay: "essay";
};
//# sourceMappingURL=resourceType.d.ts.map