/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */
import type { ResourceType } from './resourceType';

export interface Resource {
  id: number;
  type: ResourceType;
  title: string;
  /** @nullable */
  author?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  description?: string | null;
  isFree: boolean;
}
