/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * The Filmmaker's Library API
 * OpenAPI spec version: 0.1.0
 */

export type ResourceType = typeof ResourceType[keyof typeof ResourceType];


export const ResourceType = {
  book: 'book',
  video: 'video',
  film: 'film',
  podcast: 'podcast',
  website: 'website',
  essay: 'essay',
} as const;
